import 'package:tinda_test/models/user_model.dart';
import 'models.dart';
import 'package:equatable/equatable.dart';

class UserMatch extends Equatable {
  final id;
  final int userId;
  final User matchedUser;

  UserMatch(
      {required this.id, required this.userId, required this.matchedUser});

  //auto generated by Equatale
  @override
  // TODO: implement props
  List<Object?> get props => [id, userId, matchedUser];
}
